// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OnlineBusTicketReservationSystem.Models;

#nullable disable

namespace OnlineBusTicketReservationSystem.Migrations
{
    [DbContext(typeof(MyContext))]
    partial class MyContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("OnlineBusTicketReservationSystem.Models.tbl_bookedSeat", b =>
                {
                    b.Property<long>("bookedSeat_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("bookedSeat_id"), 1L, 1);

                    b.Property<string>("Bookedseat_customerName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Bookedseat_customerSeatno")
                        .HasColumnType("int");

                    b.Property<int>("bookedSeat_customerAge")
                        .HasColumnType("int");

                    b.Property<decimal>("bookedSeat_customerDiscTicketPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("bookedSeat_customerDiscountPercentage")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("bookedSeat_customerReached")
                        .HasColumnType("bit");

                    b.Property<decimal>("bookedSeat_customerTicketPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("fk_bus_id")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("bookedSeat_id");

                    b.HasIndex("fk_bus_id");

                    b.ToTable("tbl_bookedSeat");
                });

            modelBuilder.Entity("OnlineBusTicketReservationSystem.Models.tbl_bus", b =>
                {
                    b.Property<string>("bus_id")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("bus_available")
                        .HasColumnType("bit");

                    b.Property<string>("bus_category")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("bus_destionation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("bus_img_1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("bus_img_2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("bus_img_3")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("bus_noOfSeats")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<string>("bus_organizationDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("bus_organizationName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<DateTime?>("bus_startingTime")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("bus_ticketPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<long>("fk_user_id")
                        .HasColumnType("bigint");

                    b.HasKey("bus_id");

                    b.HasIndex("fk_user_id");

                    b.ToTable("tbl_bus");
                });

            modelBuilder.Entity("OnlineBusTicketReservationSystem.Models.tbl_busSeats", b =>
                {
                    b.Property<long>("busSeats_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("busSeats_id"), 1L, 1);

                    b.Property<bool>("busSeats_isBooked")
                        .HasColumnType("bit");

                    b.Property<int>("busSeats_noOfSeats")
                        .HasColumnType("int");

                    b.Property<string>("fk_bus_id")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("busSeats_id");

                    b.HasIndex("fk_bus_id");

                    b.ToTable("tbl_busSeats");
                });

            modelBuilder.Entity("OnlineBusTicketReservationSystem.Models.tbl_discount", b =>
                {
                    b.Property<long>("discount_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("discount_id"), 1L, 1);

                    b.Property<decimal?>("discount_0_TO_5")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("discount_13_TO_50")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("discount_51")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("discount_6_TO_12")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("fk_bus_id")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("discount_id");

                    b.HasIndex("fk_bus_id")
                        .IsUnique()
                        .HasFilter("[fk_bus_id] IS NOT NULL");

                    b.ToTable("tbl_discount");
                });

            modelBuilder.Entity("OnlineBusTicketReservationSystem.Models.tbl_sale", b =>
                {
                    b.Property<long>("sale_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("sale_id"), 1L, 1);

                    b.Property<string>("Sale_busCategory")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Sale_busDestination")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Sale_busOrganizationName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Sale_busStartingTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("fk_bus_id")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("sale_noOfSeatsSale")
                        .HasColumnType("int");

                    b.Property<decimal>("sale_totalAmountCollectedFromOneBus")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("sale_id");

                    b.HasIndex("fk_bus_id")
                        .IsUnique()
                        .HasFilter("[fk_bus_id] IS NOT NULL");

                    b.ToTable("tbl_sale");
                });

            modelBuilder.Entity("OnlineBusTicketReservationSystem.Models.tbl_user", b =>
                {
                    b.Property<long>("user_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("user_id"), 1L, 1);

                    b.Property<bool>("user_approved")
                        .HasColumnType("bit");

                    b.Property<bool>("user_emailVerified")
                        .HasColumnType("bit");

                    b.Property<string>("user_email_phone")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("user_name")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("user_password")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("user_role")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("user_verification_code")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("user_id");

                    b.HasIndex("user_email_phone")
                        .IsUnique();

                    b.ToTable("tbl_user");
                });

            modelBuilder.Entity("OnlineBusTicketReservationSystem.Models.tbl_bookedSeat", b =>
                {
                    b.HasOne("OnlineBusTicketReservationSystem.Models.tbl_bus", "tbl_bus")
                        .WithMany("tbl_bookedSeat")
                        .HasForeignKey("fk_bus_id");

                    b.Navigation("tbl_bus");
                });

            modelBuilder.Entity("OnlineBusTicketReservationSystem.Models.tbl_bus", b =>
                {
                    b.HasOne("OnlineBusTicketReservationSystem.Models.tbl_user", "tbl_user")
                        .WithMany("tbl_bus")
                        .HasForeignKey("fk_user_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("tbl_user");
                });

            modelBuilder.Entity("OnlineBusTicketReservationSystem.Models.tbl_busSeats", b =>
                {
                    b.HasOne("OnlineBusTicketReservationSystem.Models.tbl_bus", "tbl_bus")
                        .WithMany("tbl_busSeats")
                        .HasForeignKey("fk_bus_id");

                    b.Navigation("tbl_bus");
                });

            modelBuilder.Entity("OnlineBusTicketReservationSystem.Models.tbl_discount", b =>
                {
                    b.HasOne("OnlineBusTicketReservationSystem.Models.tbl_bus", "tbl_bus")
                        .WithMany()
                        .HasForeignKey("fk_bus_id");

                    b.Navigation("tbl_bus");
                });

            modelBuilder.Entity("OnlineBusTicketReservationSystem.Models.tbl_sale", b =>
                {
                    b.HasOne("OnlineBusTicketReservationSystem.Models.tbl_bus", "tbl_bus")
                        .WithOne("tbl_sale")
                        .HasForeignKey("OnlineBusTicketReservationSystem.Models.tbl_sale", "fk_bus_id");

                    b.Navigation("tbl_bus");
                });

            modelBuilder.Entity("OnlineBusTicketReservationSystem.Models.tbl_bus", b =>
                {
                    b.Navigation("tbl_bookedSeat");

                    b.Navigation("tbl_busSeats");

                    b.Navigation("tbl_sale");
                });

            modelBuilder.Entity("OnlineBusTicketReservationSystem.Models.tbl_user", b =>
                {
                    b.Navigation("tbl_bus");
                });
#pragma warning restore 612, 618
        }
    }
}
